### ISSUE TITLE
update codalab documentation for new azure interface

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#1]
@ckcollab 

@lukebaker found a place where the codalab instructions for azure referred to the old azure interface, not the new one.  If you think it would be helpful for the main codalab project, please update the instructions for the new azure interface.  That way we won't have this problem again and others won't have it either.

**Comment by ckcollab** [comment]
@lukebaker which section was this? We're in the process of removing the service bus entirely, so not sure we should invest much time in documenting that. I *believe* the storage instructions are still good? I used them just recently, but maybe I filled in some blanks having done it a few times before.

**Comment by lukebaker** [comment]
> We're in the process of removing the service bus entirely, so not sure we should invest much time in documenting that. I believe the storage instructions are still good?

Yes, it was the [Service Bus section](https://github.com/codalab/codalab-competitions/wiki/Dev_Set-up-data-storage#add-a-service-bus-namespace) that needs some updates. Here are some things that might be useful to include:
* Some explanation for why `azure-cli` is required to create the Service Bus.
* Have folks run `azure-cli login` before attempting to create the Service bus.
* Update the documentation for how to find the various access keys that are required to be added to the configuration file. I couldn't find the `SBS_ACCOUNT_KEY` in the current Azure portal.

**Comment by msalganik** [comment]
@ckcollab and @lukebaker 

My understanding is that this issue is now closed.  If either of you disagree, please reopen.
