### ISSUE TITLE
creating tests for leaderboard?

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#10]
@ckcollab 

@ilundberg has created some test submission files that should produce specific scores on the leaderboard.  We have been doing these tests manually.  Is this something that we can add to the CI tests?  Have you seen that before?

Thanks.

**Comment by ckcollab** [comment]
Not too easily. This would take a more significant effort (day or two of work, maybe?), if I'm understanding you. There might already be some scaffolding for doing such a test, but it's been a while since I've dug through them and I'd have to reorientate myself.

**Comment by msalganik** [comment]
OK, let's not do that.  We can do a bit manual testing.  Thanks @ckcollab.  I'm closing this issue.
