### ISSUE TITLE
prevent other folks from uploading their own competitions

### ISSUE THREAD

**Issue by lukebaker** [fragilefamilieschallenge/codalab-competitions#13]
Only approved users should be allowed to upload their own competitions.

**Comment by lukebaker** [comment]
@ckcollab is there a built-in way to prevent users from creating their own competitions? We only want approved users to be able to create their own competitions. If there's no easy / existing way to do this in codalab, I might just add HTTP authentication to the create competition URLs via nginx and give the username / password to the folks who need to create competitions. Do you have any alternate suggestions?

**Comment by ckcollab** [comment]
There's no built in way to prevent this, but should be very easy to modify the view that creates a competition to... check whether the user is an admin or not first?

`CompetitionCreationApi` class should be where you need to modify, I believe.

**Comment by lukebaker** [comment]
Thanks, @ckcollab.

@msalganik, I've updated the site to only allow admins to create competitions. At the moment, the only admin is @ilundberg (his princeton.edu email address).

**Comment by msalganik** [comment]
👍
