### ISSUE TITLE
change title of html and favicon

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#15]
We never changed the title that goes in the tab of a web browser and the favicon.

https://www.dropbox.com/s/1lu67stt8x90f85/Screenshot%202017-02-10%2014.54.59.png?dl=0

@lukebaker can you please change this to "Fragile Families Challenge powered by CodaLab" and use our FF logo.

**Comment by lukebaker** [comment]
This is all set.

**Comment by msalganik** [comment]
Thanks Luke.
