### ISSUE TITLE
remove word "competition" if possible

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#16]
I think this is an issue for @lotusgraham, but @lukebaker if you can do it go ahead (sorry not to have a clear assignment)

I'd like to remove the word "competition" if possible.  We are thinking of this as a "challenge" that include "competition" and "cooperation"

<img width="1280" alt="screenshot 2017-02-10 14 58 43" src="https://cloud.githubusercontent.com/assets/142116/22844052/4262b7f8-efaa-11e6-8dae-c6632ec2bf5f.png">

**Comment by lukebaker** [comment]
@msalganik I've removed the "Competition" subheader, changed Competition to Challenge on this page, and removed the "My Competitions" link.

**Comment by msalganik** [comment]
👍
