### ISSUE TITLE
remove "switch user" option

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#17]
There is a "switch user" option that is showing up for me.  I assume that this should not be there.  Is that helpful for testing?

@ckcollab what do you think?

<img width="1278" alt="screenshot 2017-02-10 16 04 14" src="https://cloud.githubusercontent.com/assets/142116/22844137/ae48a504-efaa-11e6-940f-e3dccf8bb563.png">

**Comment by lukebaker** [comment]
This was a result of me using dev settings. I've updated that configuration so that we're no longer using the dev settings.

**Comment by msalganik** [comment]
👍
