### ISSUE TITLE
testing infrastructure

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#2]
@ckcollab 

It looks like codalab has some kind of test suite.  Should we modify that to run on our fork?  Is that already happening?  Having the tests in place might help if/when we make modifications.

**Comment by ckcollab** [comment]
```python manage.py test```

Yeah, you should be able to just switch on CircleCI [here](https://circleci.com/add-projects), let me see if I can... nope. I need access to the organization, I hit the "request access" button but I'm unsure who will receive that request.

**Comment by msalganik** [comment]
OK, I believe I have approved the request.  Please confirm that you can do what you need now.  Or, if not, please let me know what I should do next (but beware that I've never used CircleCI before).

**Comment by ckcollab** [comment]
Cool, attached CircleCI so any new PR's we submit here will have tests run automatically.

**Comment by msalganik** [comment]
Thanks @ckcollab .  @lukebaker can you confirm that this is working as you expect?  If so, please close this issue.

**Comment by lukebaker** [comment]
Looks good.
