### ISSUE TITLE
front-end modifications

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#3]
@ckcollab 

We are going to need to do some modifications to make it clear that our site is not codalab.  It is Fragile Families Challenge powered by Codalab.  The first thing that comes to mind is the stuff in the footer (e.g., survey, about, forum, etc).  

Is this kind of customization something that you have seen before with codalab and where we could try to develop a general solution?  Or, should we develop a specific solution and hope that others can generalize it later?  Of those two options, I think I lean toward the second.

**Comment by msalganik** [comment]
I guess one way to think about this is that we are going from a multi-contest platform to a single-contest platform.

**Comment by lotusgraham** [comment]
Hey I’m Graham a frontend developer for Codalab, here’s what I have in mind. Would it work to have the homepage for http://fragile-families-challenge.codalab.org that will look just like what's in the competitions page? Here's a snapshot below of what that looks like.
![image](https://cloud.githubusercontent.com/assets/13974084/22632043/eda95538-ebe3-11e6-8014-093995bab138.png)

**Comment by ckcollab** [comment]
By the way, tried to assign this to Graham but I don't seem to have permission? May need to be an admin to do that.

**Comment by msalganik** [comment]
Welcome @lotusgraham.  That seems like a reasonable idea.  Let me check with my colleagues and get back to you on that.  More soon.

@ckcollab I've invited @lotusgraham to the org and I've made you an admin.  Let me know if you have any more problems.

**Comment by msalganik** [comment]
@lotusgraham

Yes going straight to the challenge page seems like the best thing to do (and maybe the easiest).  Thanks.

**Comment by lotusgraham** [comment]
Great, I'll work on it soon, and set up a PR.

**Comment by ckcollab** [comment]
https://github.com/codalab/codalab-competitions/pull/1680

That's what we have so far, please let us know if that works for ya! Should make sure your competition is published otherwise regular users won't be able to see it. I added a warning for this as well.

**Comment by ckcollab** [comment]
Also, set the ENV var SINGLE_COMPETITION_VIEW_PK to the specific pk you want to redirect to

**Comment by msalganik** [comment]
Thanks @ckcollab and @lotusgraham 

Is there a way that I can see what this looks like to a user?  It is hard for me to review this from just the code.

Is the easiest thing to ask @lukebaker to deploy this to our setup on Azure?

I'm excited to see it.

**Comment by ckcollab** [comment]
Easiest way to test and see how it looks for your competition is probably deploying to your server/staging server if you have one? I could setup codalabtest for this if that won't work?

**Comment by lotusgraham** [comment]
This is what that page looks like with a sample project built in. Notice the footer is gone, and the URL routes to a clean URL. Do you want this Codalab logo to be changed to your Logo? Do I understand correctly that you want to remove all Codalab branding from this page?
![codalab competition](https://cloud.githubusercontent.com/assets/13974084/22801948/eabbfed8-eedc-11e6-96ae-be62860774f3.png)

**Comment by msalganik** [comment]
Great.  Thanks @lotusgraham and @ckcollab.

@lukebaker is going to work on merging that in and then deploying it to our server.

**Comment by lotusgraham** [comment]
This is what it looks like now, added a new variation of the original footer.
![screen shot 2017-02-09 at 10 00 35 pm](https://cloud.githubusercontent.com/assets/13974084/22812899/7fb39af4-ef15-11e6-8658-c73f2af488df.png)

**Comment by msalganik** [comment]
That footer is great.  Thanks @lotusgraham.  I think that it provides a nice balance between our own branding and acknowledging the great work that CodaLab has already done.

Given that change, @lukebaker can you please grab the FFC logo from the upper left of this website: http://www.fragilefamilieschallenge.org/ and put it on the upper left of our codalab page.

Thanks.

**Comment by lukebaker** [comment]
Thanks @lotusgraham and @ckcollab. I've merged these changes into our branch and also added the FFC logo. I set it to use the test competition that I had created with earlier data from Ian as he asked that his latest data be kept private. Let me know if I should default to a different competition. Thanks!

**Comment by msalganik** [comment]
Thanks @lotusgraham and @ckcollab.  This is a great start.  I'm going to close this and start a few small issues.
