### ISSUE TITLE
practice scaling up and down on azure

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#6]
@lukebaker 

Before launch we should practice adding and shutting down workers on azure to make sure that this works as expected.

**Comment by lukebaker** [comment]
@msalganik I tested resizing the VM that we're using this morning. I went up a level (roughly 2x the resources) and then back down. There was a total of about 2 minutes of downtime each time we resized. I verified that having the additional cores improved the performance of the web site by re-running the benchmark tests that I ran previously. As expected, it nearly doubled the throughput. Adding workers is a pretty straightforward configuration tweak.

**Comment by msalganik** [comment]
Wonderful.  Thanks Luke.
