### ISSUE TITLE
price azure

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/codalab-competitions#7]
@lukebaker 

I'd like a rough sense of how much this is going to cost for Azure compute time.

Can you mock out a rough budget?  I realize that it depends a lot on load, but something rough is fine for now.  The load testing might help us put some numbers on this budget.

**Comment by lukebaker** [comment]
Here are the services that we're using in Azure:

Service | Price | Details
-----------|--------|----------
Azure VM | $57.29/mo | Standard D1 (1 core 3.5 MiB RAM)
IP Address | $2.98/mo | 1 IP Address
Storage | ~$22/mo | Estimated based on current usage

**Estimated Total:** ~$82.27/mo

I'm a little uncertain about the storage charges. I based that monthly fee on what we've been charged for a usage so far. I suspect that the first month's bill may include more details about what's being charged. There may be some additional small charges, but I've covered the primary ones.

**Comment by msalganik** [comment]
Great.  Thanks Luke.

**Comment by msalganik** [comment]
I'm closing this issue now.
